version: "2"
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - 8031:8031
    command: npm run start-server
    links:
      - db
  db:
    image: mongo:3.2.10
    ports:
      - 27017:27017
