#!/bin/bash

    osascript -e "tell application \"Terminal\"" \
            -e "tell application \"System Events\" to keystroke \"docker-compose up\" " \
            -e "tell application \"System Events\" to keystroke return" \
            -e "tell application \"System Events\" to keystroke \"t\" using {command down}" \
            -e "tell application \"System Events\" to keystroke \"npm run build-server-dev\" " \
                -e "tell application \"System Events\" to keystroke return" \
                -e "tell application \"System Events\" to keystroke \"t\" using {command down}" \
                -e "tell application \"System Events\" to keystroke \"npm start\" " \
                -e "tell application \"System Events\" to keystroke return" \
                -e "end tell"
                > /dev/null

exit;